# Created using wingetcreate 1.10.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: KnifMelti.WAU-Settings-GUI
PackageVersion: 1.7.9.1
InstallModes:
- interactive
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: WAU-Settings-GUI.exe
  PortableCommandAlias: WAU-Settings-GUI
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/KnifMelti/WAU-Settings-GUI/releases/download/v1.7.9.1/WAU-Settings-GUI-v1.7.9.1.zip
  InstallerSha256: 91e22712f592964fee773b3bf4d6d9f356010de5a4c6b92a4cf446618490058b
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.10.0
