name: Create Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Create zip from subdirectory
      run: |
        cd "Sources/WAU Settings GUI"
        zip -r "../../WAU-Settings-GUI-${{ github.event.release.tag_name }}.zip" .
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./WAU-Settings-GUI-${{ github.event.release.tag_name }}.zip
        asset_name: WAU-Settings-GUI-${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip
        
