name: Create Release

on:
  release:
    types: [created]

permissions:
  contents: write
  id-token: write  # Required for keyless signing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.6.0
      with:
        cosign-release: 'v2.2.4'
    
    - name: Create zip from subdirectory
      run: |
        cd "Sources/WAU Settings GUI"
        zip -r "../../WAU-Settings-GUI-${{ github.event.release.tag_name }}.zip" .
    
    - name: Sign zip file with Cosign
      run: |
        cosign sign-blob --yes \
          --output-signature WAU-Settings-GUI-${{ github.event.release.tag_name }}.zip.sig \
          --output-certificate WAU-Settings-GUI-${{ github.event.release.tag_name }}.zip.pem \
          WAU-Settings-GUI-${{ github.event.release.tag_name }}.zip
    
    - name: Upload Release Assets
      run: |
        gh release upload ${{ github.event.release.tag_name }} \
          WAU-Settings-GUI-${{ github.event.release.tag_name }}.zip \
          WAU-Settings-GUI-${{ github.event.release.tag_name }}.zip.sig \
          WAU-Settings-GUI-${{ github.event.release.tag_name }}.zip.pem
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
